---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.1'

inputs:
- name: grootfs-release-master
- name: grootfs-release-version

outputs:
- name: build-grootfs

run:
  path: grootfs-release-master/src/code.cloudfoundry.org/grootfs/ci/scripts/build-grootfs.sh
  user: root
