---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
- name: grootfs-git-repo
  path: src/code.cloudfoundry.org/grootfs

outputs:
- name: build-grootfs

run:
  path: src/code.cloudfoundry.org/grootfs/ci/scripts/build-grootfs.sh
