---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
- name: grootfs-release-master
- name: grootfs-release-version

run:
  path: grootfs-release-master/src/code.cloudfoundry.org/grootfs/ci/scripts/check-version.sh
  user: root
