---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.0'

inputs:
- name: grootfs-release-develop
- name: version

run:
  path: grootfs-release-develop/src/code.cloudfoundry.org/grootfs/ci/scripts/check-version.sh
  user: root
