---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/golang-ci
    tag: latest

inputs:
- name: grootfs-git-repo
  path: src/code.cloudfoundry.org/grootfs

run:
  path: make
  args: [go-vet]
  dir: src/code.cloudfoundry.org/grootfs
