---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.0'

inputs:
- name: grootfs-git-repo
  path: src/code.cloudfoundry.org/grootfs

run:
  path: src/code.cloudfoundry.org/grootfs/ci/scripts/go-vet.sh
