---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: v0.13.0

inputs:
  - name: grootfs-git-repo
    path: src/code.cloudfoundry.org/grootfs

params:
  REGISTRY_USERNAME:
  REGISTRY_PASSWORD:
  VOLUME_DRIVER: btrfs

run:
  path: src/code.cloudfoundry.org/grootfs/ci/scripts/integration-tests.sh
  user: root
