---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci
    tag: latest

inputs:
  - name: grootfs-git-repo
    path: src/code.cloudfoundry.org/grootfs
  - name: grootfs-bench-git-repo
    path: src/code.cloudfoundry.org/grootfs-bench

run:
  path: src/code.cloudfoundry.org/grootfs/ci/scripts/performance-tests.sh
  user: groot
