---
resources:
- name: grootfs-git-repo
  type: git
  source:
    uri: https://github.com/cloudfoundry/grootfs
    branch: master
    ignore_paths:
    - ci/pipeline.yml

- name: slack-alert
  type: slack-notification-docker
  source:
    url: {{slack-alert-url}}

- name: grootfs-tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1661239"
    token: {{garden-tracker-token}}

- name: grootfs-version
  type: semver
  source:
    bucket: grootfs-ci-meta
    key: grootfs/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: eu-west-1
    initial_version: 0.1.0-dev.1
    driver: s3

- name: grootfs-gh-release
  type: github-release
  source:
    user: {{gr-github-release-username}}
    repository: grootfs
    access_token: {{github-access-token}}
    drafts: true

jobs:
- name: grootfs
  public: true
  plan:
  - aggregate:
    - get: grootfs-version
      params: { pre: 'dev' }
    - get: grootfs-git-repo
      trigger: true
  - put: grootfs-version
    params: { file: grootfs-version/number }
  - task: grootfs
    file: grootfs-git-repo/ci/tasks/grootfs.yml
    on_failure:
      put: slack-alert
      params:
        username: Thanos
        icon_url: http://www.comicsblend.com/wp-content/uploads/2013/04/thanos.jpg
        channel: "#garden"
        text: "<!subteam^S1U0HSJ9E|grootfsteam>: I've destroyed your build. Come and get me!"
  - put: grootfs-tracker
    params:
      repos:
      - grootfs-git-repo

- name: create-release
  plan:
  - get: grootfs-git-repo
    passed: [grootfs]
  - get: grootfs-version
    passed: [grootfs]
    params: { bump: final }
  - task: build-grootfs
    file: grootfs-git-repo/ci/tasks/build-grootfs.yml
  - put: grootfs-gh-release
    params:
      name: grootfs-version/number
      tag: grootfs-version/number
      tag_prefix: v
      globs: build-grootfs/grootfs.tgz
  - put: grootfs-version
    params: { file: grootfs-version/number }


resource_types:
- name: slack-notification-docker
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
