store_path: /var/lib/grootfs/btrfs
driver: btrfs
btrfs_bin: /bin/btrfs
drax_bin: /home/ubuntu/drax
newuidmap_bin: /usr/local/bin/newuidmap
newgidmap_bin: /usr/local/bin/newgidmap
log_level: debug
log_file:
metron_endpoint: 127.0.0.1:1234
clean:
  threshold_bytes: 1048576
  ignore_images: []
create:
  insecure_registries: []
  with_clean: true
  uid_mappings:
  - "0:4294967294:1"
  - "1:1:4294967293"
  gid_mappings:
  - "0:4294967294:1"
  - "1:1:4294967293"
